# Generated by Django 2.0.13 on 2020-08-08 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200804_2115'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todaytalk',
        ),
    ]
