# Generated by Django 2.0.13 on 2020-09-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
