# Generated by Django 2.0.13 on 2020-09-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_temp_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_max_humid',
            field=models.FloatField(default='0000-00-00'),
        ),
    ]
