# Generated by Django 2.0.13 on 2020-09-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200903_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='good_max_humid',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='temp',
            name='date',
            field=models.DateField(default='1970-01-02'),
        ),
    ]
