# Generated by Django 2.0.13 on 2020-09-03 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200903_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temp',
            name='date',
        ),
    ]
